# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoopImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.CharField(max_length=50)),
                ('img2', models.CharField(max_length=50)),
                ('img3', models.CharField(max_length=50)),
                ('img4', models.CharField(max_length=50)),
                ('bg', models.CharField(max_length=50)),
            ],
        ),
    ]
