# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20190120_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rwm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rwmID', models.CharField(max_length=50)),
                ('rwmName', models.CharField(max_length=50)),
                ('rwmPricetype', models.CharField(max_length=50)),
                ('rwmPrice', models.CharField(max_length=50)),
                ('rwmdel', models.CharField(max_length=50)),
                ('rwmImg', models.CharField(max_length=50)),
                ('bigImg', models.CharField(max_length=50)),
            ],
        ),
    ]
