# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwm',
            name='rwmImg',
            field=models.CharField(max_length=256),
        ),
    ]
